paths:
  /api/products:
    get:
      summary: Get all products
      tags:
        - Products
      description: Retrieves a list of all available products.
      responses:
        "200":
          description: A list of products

    post:
      summary: Add a new product
      tags:
        - Products
      description: Creates a new product.
      responses:
        "200":
          description: Product created successfully
        "400":
          description: Invalid product data

  /api/products/{pid}:
    get:
      summary: Get product by ID
      tags:
        - Products
      description: Retrieves a specific product by its ID.
      responses:
        "200":
          description: Product found
        "404":
          description: Product not found

    put:
      summary: Update a product
      tags:
        - Products
      description: Updates an existing product.
      responses:
        "200":
          description: Product updated successfully
        "400":
          description: Invalid product data
        "404":
          description: Product not found

    delete:
      summary: Delete a product
      tags:
        - Products
      description: Deletes a specific product by its ID.
      responses:
        "200":
          description: Product deleted successfully
        "404":
          description: Product not found
